apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: rag-project
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30990
  type: NodePort
