FROM ghcr.io/mlflow/mlflow:v2.15.1

RUN pip install --no-cache-dir boto3 psycopg2-binary

WORKDIR /mlflow

EXPOSE 5000

CMD ["mlflow", "server", \
     "--host", "0.0.0.0", \
     "--port", "5000", \
     "--backend-store-uri", "postgresql+psycopg2://airflow:airflow@postgresql-ha:5432/airflow", \
     "--default-artifact-root", "s3://mlflow-bucket/", \
     "--serve-artifacts"]
