apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
  namespace: rag-project
spec:
  selector:
    app: qdrant
  ports:
    - name: http
      port: 6333
      targetPort: 6333
      nodePort: 30333
    - name: grpc
      port: 6334
      targetPort: 6334
  type: NodePort
