apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: rag-project
data:
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"
  AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: "true"
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"
  AWS_ENDPOINT_URL: "http://minio-service:9000"
  AWS_DEFAULT_REGION: "us-east-1"
  PYTHONPATH: "/opt/airflow/src"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  DEBUG: "False"
  ENVIRONMENT: "production"
