defaults:
  - download: download
  - chunking: chunking
  - embeddings: embeddings
  - dag: dag
  - qdrant_setup: qdrant_setup
  - generator: generator
  - retriever: retriever
  - test_data: test_data
  - qdrant: qdrant
  - minio: minio
  - mlflow: mlflow
  - eval: eval
  - _self_
