apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-exporter
  namespace: rag-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-exporter
  template:
    metadata:
      labels:
        app: celery-exporter
    spec:
      containers:
        - name: celery-exporter
          image: danihodovic/celery-exporter:latest
          args:
            - --broker-url=redis://redis:6379/0
            - --port=9808
          ports:
            - containerPort: 9808
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "50m"
