apiVersion: v1
kind: Service
metadata:
  name: rag-service
  namespace: rag-project
spec:
  selector:
    app: rag-service
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800
  type: NodePort
